name: stock_mts_mobile
description: "Stock_MTS_TA mobile client (Flutter, Android-only, personal use)."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  fl_chart: ^1.0.0
  k_chart_plus: ^1.0.3
  local_auth: ^2.3.0
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
